-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgTZipGTebl0sqTe3/
PF+BMQ6ddu8R5NEMocqMRY19MWqgCgYIKoZIzj0DAQehRANCAATd+fZfdQyMxNqZ
F95MRnWFF3/PuiUl6csGmBE76DHttBX/PYLJHAjqqCnlVjfFdF4CWYV45OVGYbRe
zIpTEfTj
-----END PRIVATE KEY-----
